package com.example.transittripprocessor.model;

import java.util.Objects;

/**
 * An unordered pair of stops.
 *
 * <p>The constructor always stores the lower enum value first. Therefore
 * {@code new StopPair(STOP_1, STOP_2)} and
 * {@code new StopPair(STOP_2, STOP_1)} contain identical record components.
 * The {@code equals} and {@code hashCode} methods generated by {@link Record}
 * consequently treat them as the same map key.</p>
 */
public record StopPair(StopId first, StopId second) {

    public StopPair {
        Objects.requireNonNull(first, "first must not be null");
        Objects.requireNonNull(second, "second must not be null");

        // Normalize both travel directions to same order
        if (first.ordinal() > second.ordinal()) {
            StopId temporary = first;
            first = second;
            second = temporary;
        }
    }

    /**
     * Returns whether this pair contains the given stop.
     * This makes it possible to find all routes connected to a stop, such as
     * when determining the highest possible fare for an incomplete trip.
     */
    public boolean includes(StopId stopId) {
        return first == stopId || second == stopId;
    }
}
